### ISSUE TITLE
Adopt jade-react-compiler?

### ISSUE THREAD

**Issue by mikepb** [jadejs/react-jade#42]
Hi all,

I wrote a Jade-to-React compiler a while ago:
https://github.com/mikepb/jade-react-compiler

It parses and directly manipulates the JS AST to supports interpolation and other goodies.

Would you be open to adopting the project into the jadejs organization?

Best,
Michael

**Comment by ForbesLindesay** [comment]
Hi @mikepb,

It's great to hear someone else working on the same problem.  I think that react-jade is actually a somewhat more complete implementation so we'll stick with this one as the official react-jade compiler.  The missing features are very much just missing because nobody's got round to implementing them yet though, so if you would like to contribute, just open a pull request.

Thanks,
Forbes
