### ISSUE TITLE
Components nesting

### ISSUE THREAD

**Issue by kinday** [jadejs/react-jade#52]
It seems like we cannot nest components like this:
```jade
Wrapper(theme='dark')
	Info(data=this.state.data.info)
```

Would anyone mind to help me if I’m doing something wrong or point to the problem making `react-jade` unable to render things this way?

**Comment by emilis** [comment]
It should be able to nest components this way (at least my fork of react-jade is able).

The way it works, inside Wrapper you could use code like this:

*one child*:

```jade
div.your-wrapper
    = children
```

*zero to multiple children*:

```jade
- var childArray = !children ? [] : children.length ? children : [children];
div.your-wrapper
    each child in childArray
        = child
```

**Comment by kinday** [comment]
@emilis, thanks for your answer, but I guess you missed the point.

I need a possibility to make something like this:
```jade
// sidebar.js
Wrapper
    Child

Wrapper
    AnotherChild

Wrapper(theme='dark')
    EmoChild
```

Or imagine that `Wrapper` is something about common modal window stuff and `Child`, `AnotherChild`, `EmoChild` are different components I want to put into this common modal wrapper.

**Comment by emilis** [comment]
@kinday the possibility is there.

I think I made a mistake in my code: you should probably use `this.props.children` instead of `children` in the code snippets (it's the difference between my fork and stock react-jade: I import props as locals).

There is this React.js feature called [children](https://facebook.github.io/react/docs/multiple-components.html#children) available as `this.props.children`. It allows the thing you want: passing child components into parent component.

So I think this should be correct with stock react-jade:

*One child component inside Wrapper's `render()`:*

```jade
div.your-wrapper
    = this.props.children
```

*Multiple child components inside Wrapper's `render()`:*

```jade
- var childArray = !this.props.children ? [] : this.props.children.length ? this.props.children : [this.props.children];
div.your-wrapper
    each child in childArray
        = child
```

When you put the code above into the `render()` method of your `Wrapper` component, you should be able to use it in the way you described.

**Comment by jeromew** [comment]
@kinday I am surprised it should work imho. could you post a stripped down working example showing the problem (showing how you init react-jade + how you implement the components)

**Comment by kinday** [comment]
@emilis, thanks a lot! Worked like a charm!

@jeromew, it works with `this.props.children`. We can close the issue if you don’t need my example to investigate anything.

**Comment by jeromew** [comment]
@kinday ok let's close this for now if this solution works for you. I'll do my own digging on the side.

**Comment by elviocb** [comment]
Can someone post a code snippet of nested components? Would help a lot ppl are trying to get used to it
